index:
    path: /
    controller: App\Controller\DefaultController::index
category_page:
    path: /category/{slug}
    controller: App\Controller\CategoryPageController::index
    requirements:
        page: .+